blank_issues_enabled: false

contact_links:
  - name: Community Discussions
    url: https://github.com/generation-software/.github/discussions
    about: Check out this page for browsing conversations, asking questions, and posting answers without opening issues.
  - name: Open Source Community
    url: https://github.com/generation-software
    about: Read this page for information on Generation Software open source in general.
