blank_issues_enabled: false

contact_links:
  - name: Community Discussions
    url: https://github.com/paion-data/.github/discussions
    about: Check out this page for browsing conversations, asking questions, and posting answers without opening issues.
  - name: Company Landing Page
    url: https://paion-data.com
    about: Read this page for information on Paion Data in general.
  - name: Service Status
    url: https://status.paion-data.dev/
    about: Please check this out if any of our online services is not operating in expectation.
